// One-time tutorial hints shown the first time a mechanic matters.
import { S } from './state.js';
import { bus } from './bus.js';
import { prompt } from './access.js';

export const TIPS = {
  sneak: 'HOLD {KeyC} TO SNEAK: UNAWARE FOES TAKE 3X DAMAGE.\nROLL ({Space}) THROUGH A TELEGRAPHED HIT.',
  stamina: 'STAMINA REFILLS WHEN YOU STOP ACTING.\nPRESS {Digit3} FOR A STAMINA POTION.',
  perks: 'OPEN THE PACK ({KeyI}) AND SPEND YOUR PERK POINT\nON THE PERKS TAB.',
  lock: 'LOCKPICKING: PRESS {KeyE} WHEN THE MARKER\nIS INSIDE THE GREEN ZONE.',
  block: 'HOLD {KeyF} TO BLOCK. RAISE THE SHIELD JUST BEFORE\nA HIT TO PARRY AND STAGGER THE ATTACKER.',
  bow: 'HOLD {KeyK} TO DRAW, RELEASE TO SHOOT.\nARROWS THAT MISS CAN BE PICKED UP AGAIN.',
  night: 'NIGHT: ENEMIES SEE LESS FAR WHEN YOU SNEAK.\nVILLAGERS ARE INDOORS.',
  potion: 'POTIONS: {Digit1} HEALTH, {Digit2} MANA, {Digit3} STAMINA.\nRESTING AT A CAMPFIRE ALSO HEALS.',
  rest: 'RESTING SAVES YOUR GAME AND SETS\nWHERE YOU WAKE IF YOU FALL.',
  reaver: 'RIME REAVER: IT WAITS OUT YOUR ROLL.\nSTEP BACK, ROLL LATE, OR HIT IT FROM RANGE.',
  knight: 'RIME KNIGHT: ARMOUR SHRUGS OFF BLOWS.\nPARRY ITS SWING WITH A SHIELD ({KeyF}) TO OPEN IT UP.',
  fencer: 'SNOW FENCER: IT SIDESTEPS YOUR SWING.\nBAIT A SWING, THEN STRIKE, OR USE BOW AND SPELLS.',
  imp: 'CINDER IMP: IT RUNS AT YOU AND BURSTS.\nKILL IT AT RANGE OR ROLL AWAY FROM THE FUSE.',
  necro: 'GRAVE CALLER: IT RAISES THE DEAD EVERY FEW SECONDS.\nREACH IT FIRST.',
  frostworm: 'FROST WORM: IT TUNNELS UNDER THE SNOW.\nMOVE OFF THE MARK BEFORE IT SURFACES.',
  tracks: 'GIANT TRACKS! SOMETHING WALKS A LOOP\nBETWEEN THE CAMPS. FOLLOW THE PRINTS.',
  elk: 'THE WINTER ELK: IT CHARGES IN A STRAIGHT LINE.\nSTEP SIDEWAYS AT THE LAST MOMENT, THEN STRIKE.',
  troll: 'THE BRIDGE TROLL REGENERATES.\nKEEP THE DAMAGE COMING. FIRE HURTS IT MOST.',
  bearcub: 'A BEAR CUB! HURT IT AND ITS MOTHER COMES.\nTHE MOTHER CRUSHES SHIELDS. ROLL, DO NOT BLOCK.',
  wyvern: 'WYVERN: IT CIRCLES, THEN DIVES.\nSTRIKE AS IT PASSES OR SHOOT IT DOWN.',
  shroom: 'SPORE MOTHER: IT SEEDS THE GROUND WITH BURSTS.\nKEEP MOVING AND STRIKE FROM RANGE.',
  golem: 'RIME GOLEM: ICE ARMOUR. PARRY IT, STAGGER IT,\nOR USE LIGHTNING.',
  lynx: 'SHADOW LYNX: IT HIDES IN THE SNOW AND POUNCES.\nLISTEN FOR THE GROWL AND ROLL.',
  bear: 'SNOW BEAR: BIG, SLOW SWINGS.\nROLL THROUGH THEM AND STRIKE BACK.',
  quest: 'PRESS {KeyO} FOR THE JOURNAL.\nPRESS {KeyE} ON A QUEST TO TRACK IT.',
};
export function tip(id) {
  if (S.tips[id] || !TIPS[id]) return;
  S.tips[id] = true;
  bus.emit('hint', TIPS[id].replace(/\{(\w+)\}/g, (_, c) => prompt(c)));
}
