extends Node
## Global signal hub. Systems talk through here instead of holding references
## to each other, so any piece (HUD, audio, camera, VFX) can listen in.

@warning_ignore_start("unused_signal")
signal player_joined(player: Player)
signal player_left(slot: int)
signal player_died(player: Player)
signal player_revived(player: Player)
signal player_jumped(player: Player)
signal player_landed(player: Player)
signal player_hard_landed(player: Player, speed: float)
signal player_ground_pounded(player: Player, position: Vector2)
signal player_slid(player: Player)
signal player_ledge_grabbed(player: Player)
signal player_wall_jumped(player: Player)
signal player_wall_ran(player: Player)
signal player_character_changed(player: Player)
signal lum_collected(slot: int, position: Vector2)
signal lums_changed(total: int)
signal enemy_defeated(enemy: Node2D, by: Player)
signal enemy_hit(enemy: Node2D, by: Player)
signal enemy_spawned(enemy: Node2D)
signal enemy_shot(enemy: Node2D)
signal player_punched(player: Player, power: float)
signal level_started(level: Node2D)
signal enemy_blocked(enemy: Node2D, by: Player)
signal projectile_reflected(projectile: Node2D, by: Player)
signal punch_landed(player: Player, target: Node2D, power: float)
signal breakable_broken(breakable: Node2D, by: Player)
signal checkpoint_reached(position: Vector2)
signal gem_collected(index: int, slot: int, position: Vector2)
signal snoozling_rescued(position: Vector2)   ## a caged Snoozling was freed
signal stomp_chain(player: Player, count: int)   ## 2+ enemy stomps without touching the ground
signal boss_changed(boss_name: String, health: int, max_health: int, active: bool)  ## drives the HUD boss bar
signal level_completed(results: Dictionary)
signal pause_requested(slot: int, message: String)
signal level_reset
signal device_lost(slot: int)
signal player_head_bounced(top: Player, bottom: Player)
signal pad_bounced(player: Player, pad: Node2D, pounding: bool)
signal player_swung(player: Player)
signal player_splashed(player: Player, position: Vector2)
signal cannon_fired(cannon: Node2D, player: Player)
signal secret_found(secret: Node2D)
signal balloon_changed(player: Player, holding: bool)
signal parachute_changed(player: Player, holding: bool)  ## dandelion puff grabbed / let go
signal players_teleported(position: Vector2)
signal key_picked(key: Node2D, player: Player)
signal door_unlocked(door: Node2D)
signal switch_toggled(switch: Node2D, on: bool)
## Juice requests (anyone may emit; CoopCamera / Vfx listen).
signal screen_shake(amount: float)
signal hit_stop(duration: float)
@warning_ignore_restore("unused_signal")
