import { launch } from './harness.mjs';
const h = await launch();
await h.open('scene=game&map=village&spawn=start');
await h.sleep(800);
await h.ev(async () => { (await import('/src/systems/settings.js')).settings.mouse = true; const g = window.__ff.game.scene.getScene('Game'); g.player.setPosition(300, 250); window.__ff.S.sp = 100; });
const box = await h.page.locator('canvas').boundingBox();
console.log(box);
await h.page.mouse.move(box.x + box.width * 0.9, box.y + box.height * 0.5);
await h.sleep(200);
console.log(await h.ev(() => { const g = window.__ff.game.scene.getScene('Game'); const p = g.input.activePointer; return { wx: p.worldX, wy: p.worldY, x: p.x, y: p.y, px: g.player.x, py: g.player.y, face: g.player.face, cam: [g.cameras.main.scrollX, g.cameras.main.scrollY] }; }));
await h.page.mouse.click(box.x + box.width * 0.9, box.y + box.height * 0.5);
await h.sleep(40);
console.log(await h.ev(() => { const g = window.__ff.game.scene.getScene('Game'); return { face: g.player.face, sw: !!g.player.swing }; }));
await h.close();
