import { launch, check, failCount } from './harness.mjs';
const h = await launch();
await h.open('scene=game&map=village&spawn=start');
await h.sleep(800);
const G = (fn, a) => h.ev(fn, a);
const kill = () => G(() => { const g = window.__ff.game.scene.getScene('Game'); g.player.mode = 'free'; g.player.invuln = 0; window.__ff.S.hp = 5; g.player.hurt(50, g.player.x + 10, g.player.y); });
await G(() => { window.__ff.S.follower = true; window.__ff.game.scene.getScene('Game').spawnFollower(); window.__ff.S.flags.introDone = true; });
await h.sleep(300);
await kill();
await h.sleep(500);
check('the player goes down first', await G(() => window.__ff.game.scene.getScene('Game').player.mode === 'dead'));
await h.sleep(1200);
const up = await G(() => { const g = window.__ff.game.scene.getScene('Game'); return { mode: g.player.mode, hp: window.__ff.S.hp, max: window.__ff.S.maxHp, resp: !!g.respawning }; });
check('Ragna pulls you back up with 40% health', up.mode === 'free' && up.hp === Math.round(up.max * 0.4) && !up.resp, JSON.stringify(up));
await kill();
await h.sleep(3200);
const second = await G(() => { const g = window.__ff.game.scene.getScene('Game'); return !!g.respawning || g.scene.isActive('Game') && g.player?.mode !== 'free'; });
check('a second fall inside the cooldown is a real death (respawn)', second);
check('no page errors', h.errors.length === 0, h.errors.join('\n'));
await h.close();
console.log(failCount() ? 'COMPANION FAILED' : 'COMPANION PASSED');
process.exit(failCount() ? 1 : 0);
