import { launch, check, failCount } from './harness.mjs';
const h = await launch();
await h.open('scene=game&map=village&spawn=start');
await h.sleep(700);
const G = (fn, a) => h.ev(fn, a);
const press = (c) => h.ev((c) => window.__ff.keys._press(c), c);
const rel = (c) => h.ev((c) => window.__ff.keys._release(c), c);
const tap = async (c, ms = 80) => { await press(c); await h.sleep(ms); await rel(c); await h.sleep(70); };
const tut = () => G(() => window.__ff.S.flags.tut);
await G(async () => { window.__t = await import('/src/systems/tutorial.js'); window.__ff.S.flags.introDone = true; window.__t.startTutorial(); const g = window.__ff.game.scene.getScene('Game'); g.player.setPosition(300, 250); g.player.mode = 'free'; g.player.invuln = 99; });
await h.sleep(300);
check('tutorial starts at the move step', (await tut()) === 'move');
check('move hint is shown', await G(() => !!window.__ff.game.scene.getScene('Hud').hint));
await press('KeyD'); await h.sleep(700); await rel('KeyD');
check('walking advances to roll', (await tut()) === 'roll');
await tap('Space', 60); await h.sleep(300);
check('rolling spawns the lone wolf (fight step)', (await tut()) === 'fight' && await G(() => window.__ff.game.scene.getScene('Game').enemies.getChildren().filter((e) => e.tutorial).length === 1));
const wolf = await G(() => { const e = window.__ff.game.scene.getScene('Game').enemies.getChildren().find((x) => x.tutorial); return { hp: e.hp, max: e.maxHp, alerted: e.alerted }; });
check('the tutorial wolf is weakened and already hunting you', wolf.max < 50 && wolf.alerted, JSON.stringify(wolf));
await G(() => { const g = window.__ff.game.scene.getScene('Game'); const e = g.enemies.getChildren().find((x) => x.tutorial); e.hp = 0; e.dead = true; });
await h.sleep(300);
check('killing the wolf finishes the tutorial', (await tut()) === 'done' && await G(() => window.__ff.S.flags.tutDone === true));
await h.sleep(500);
check('tutorial never spawns again', await G(() => window.__ff.game.scene.getScene('Game').enemies.getChildren().filter((e) => e.tutorial && !e.dead).length === 0));
check('no page errors', h.errors.length === 0, h.errors.join('\n'));
await h.close();
console.log(failCount() ? 'TUTORIAL FAILED' : 'TUTORIAL PASSED');
process.exit(failCount() ? 1 : 0);
